download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",
              "power.zip", method = "curl")
unzip("power.zip")
power <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
newpower <- power[power$Date %in% c("1/2/2007","2/2/2007") ,]
datesandtimes <- strptime(paste(newpower$Date, newpower$Time), "%d/%m/%Y %H:%M:%S") 
gapower <- as.numeric(newpower$Global_active_power)
grpower <- as.numeric(newpower$Global_reactive_power)
sub1 <- as.numeric(newpower$Sub_metering_1)
sub2 <- as.numeric(newpower$Sub_metering_2)
sub3 <- as.numeric(newpower$Sub_metering_3)
voltages <- as.numeric(newpower$Voltage)
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(datesandtimes, gapower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datesandtimes, voltages, type="l", xlab="datetime", ylab="Voltage")
plot(datesandtimes, sub1, type="l", xlab = "", ylab="Energy sub metering")
lines(datesandtimes, sub2, type="l", col="red")
lines(datesandtimes, sub3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datesandtimes, grpower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()